spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:55994/personal_store_management_db
    username: root
    password: gFWVHxPefgczQTDCNohoaIylWEdFwxMU
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: SpringBoot-personal-store-management

server:
  port: 2003
  servlet:
    context-path: /api