spring:

#cấu hình database
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=PersonalStore
    username: sa
    password: Gi@khoi221203
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

#cấu hình jpa
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#tên ứng dụng
  application:
    name: personal-store-management-project

#cấu hình port cho server
server:
  port: 2003
  servlet:
    context-path: /api

#biến open api
open:
  api:
    title: Vựa mít - yến Khoa
    url: http://localhost:2003/api
    version: 1.0
    server: http://localhost:2003/api

#biến frontend
frontend:
  url:
    - http://localhost:5173/
    - https://vuamityenkhoa.vercel.app
#biến mail
mail:
  host: smtp.gmail.com
  port: 587
  username: giakhoi060708@gmail.com
  password: pqho vqrn nhco pbiz
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true