spring:
  # Database
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=PersonalStoreManagement}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true

# Application
  application:
    name: personal-store-management-project
  config:
    import: application-secrets.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server
server:
  port: 2003
  servlet:
    context-path:

#biến open api
open:
  api:
    title: Vựa mít - yến Khoa
    url: http://localhost:2003/
    version: 1.0
    server: http://localhost:2003/

# Config CORS
frontend:
  url:
    - http://localhost:5173/
    - https://vuamityenkhoa.vercel.app

# Config JWT
jwt:
  secret: ${JWT_SECRET:}
  expiration: 86400000


